-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 22:05:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema garrobo_security
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema garrobo_security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `garrobo_security` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `garrobo_security` ;

-- -----------------------------------------------------
-- Table `garrobo_security`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`USER` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A:Activo, B:Baja, I:Inactivo',
  `create_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garrobo_security`.`RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`RESOURCE` (
  `resource_name` VARCHAR(100) NOT NULL,
  `path` VARCHAR(200) NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A:Activo, I:Inactivo, B:Baja',
  `last_update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`resource_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garrobo_security`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`ROL` (
  `rol_name` VARCHAR(100) NOT NULL,
  `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A:Activo, I:Inactivo, B:Baja',
  `last_update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`rol_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garrobo_security`.`PRIVILEGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`PRIVILEGE` (
  `rol` VARCHAR(100) NOT NULL,
  `resource` VARCHAR(100) NOT NULL,
  `last_update` TIMESTAMP NOT NULL,
  INDEX `privilege_rol_idx` (`rol` ASC) VISIBLE,
  INDEX `privilege_resource_idx` (`resource` ASC) VISIBLE,
  PRIMARY KEY (`rol`, `resource`),
  CONSTRAINT `privilege_rol_fk`
    FOREIGN KEY (`rol`)
    REFERENCES `garrobo_security`.`ROL` (`rol_name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `privilege_resource_fk`
    FOREIGN KEY (`resource`)
    REFERENCES `garrobo_security`.`RESOURCE` (`resource_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garrobo_security`.`ROLE_MEMBERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`ROLE_MEMBERS` (
  `user` VARCHAR(20) NOT NULL,
  `rol` VARCHAR(100) NOT NULL,
  `last_update` TIMESTAMP NOT NULL,
  INDEX `role_members_user_idx` (`user` ASC) VISIBLE,
  INDEX `role_members_rol_idx` (`rol` ASC) VISIBLE,
  PRIMARY KEY (`user`, `rol`),
  CONSTRAINT `role_members_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `garrobo_security`.`USER` (`username`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `role_members_rol_fk`
    FOREIGN KEY (`rol`)
    REFERENCES `garrobo_security`.`ROL` (`rol_name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `garrobo_security`.`HISTORY_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `garrobo_security`.`HISTORY_USER` (
  `history_user_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(60) NOT NULL,
  `date` DATETIME NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`history_user_id`),
  INDEX `history_user_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `history_user_fk`
    FOREIGN KEY (`username`)
    REFERENCES `garrobo_security`.`USER` (`username`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
